# Generated by Django 5.1.4 on 2025-02-21 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commande',
            old_name='complete',
            new_name='statut',
        ),
    ]
