# Generated by Django 5.1.4 on 2025-02-24 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0002_rename_complete_commande_statut'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commande',
            old_name='statut',
            new_name='complete',
        ),
    ]
